version: '3.1'
services:
  aria2:
    image: xujinkai/aria2-with-webui
    container_name: aria2_macvlan_test
    restart: always
    privileged: true  # add for centos7 firewall.
    environment:
     SECRET : 1 # secret: TO BE CHANGED
    networks:
      app_net:
        ipv4_address: 255.255.240.10 # just visit http://192.168.1.132
networks:
  app_net:
    driver: macvlan
    driver_opts:
      parent: en0
    ipam:
      config:
        - subnet: 30.43.96.1/20
