version: '3.1'
services:
  aria2:
    image: xujinkai/aria2-with-webui
    container_name: aria2_macvlan_test
    restart: always
    privileged: true  # add for centos7 firewall.
    environment:
     SECRET : 1 # secret: TO BE CHANGED
    networks:
      app_net:
        ipv4_address: 192.168.1.132 # just visit http://192.168.1.132
networks:
  app_net:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.1.1/24
