version: '3.1'

services:

  v2ray:
    image: v2ray/official
    container_name: v2ray_server
    restart: always
    privileged: true  # add for centos7 firewall.
    command: v2ray -config=/etc/v2ray/server_config.json
    ports:
      - 8085:8888 # export service port to host machine, host_port:container_port.
    volumes:
      - ./v2ray:/etc/v2ray
      #- /etc/v2ray/v2ray.crt:/etc/v2ray/v2ray.crt
      #- /etc/v2ray/v2ray.key:/etc/v2ray/v2ray.key

